<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-12-01 16:01
=======
# Generated by Django 4.2.7 on 2025-12-01 22:55
>>>>>>> b11942a3962be8c18d2f680c404f11a716b0fa4e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_fix_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
